repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.0
    hooks:
      - id: uv-lock

  - repo: https://github.com/ninoseki/uv-sort
    rev: v0.1.1
    hooks:
      - id: uv-sort
    files: ^(pyproject\.toml)$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
